#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var argv = require('optimist')
    .usage('\nUsage: scintilla [options] (scintilla needs to run with root privileges)')
    .check(function(){ if (process.argv.length == 2) return false })
    .alias('p', 'pid')
    .describe('p', 'Process Id of the node application hosting leveldb')
    .alias('l', 'list')
    .describe('l', 'list the pids for all the running node processes')
    .alias('a', 'all')
    .describe('a', 'Try and attach to all node processes. If new ones are created while running then scintilla will attach')
    .argv


if(argv.l) {
 console.log('Collecting node processes');
 // run pgrep node
 // for each line in pgrep node 
 // run ps -p 11880 -o args
 // run pwdx 11880
}

if(arg.a) {
  //run pgrep node
  //for each process
  //add to process array 
  //Try and run script for process
  //setInterval and try and run script against new ones. 
} 

if(arg.p) {
  // Call the script with the pid provided
  // sudo dtrace -s ./scintilla.d arg.p | c++filt
}
